# Generated by Django 2.1.4 on 2019-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('mime', models.CharField(max_length=50)),
                ('filesize', models.IntegerField()),
                ('num_downloads', models.IntegerField(default=1)),
            ],
        ),
    ]
