# Generated by Django 2.1.4 on 2019-01-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_lista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
