# Generated by Django 2.1.4 on 2019-01-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_auto_20190101_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='items',
        ),
        migrations.AddField(
            model_name='listaitem',
            name='lista',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lista.Lista'),
            preserve_default=False,
        ),
    ]
