# Generated by Django 2.1.4 on 2019-01-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_auto_20190101_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaitem',
            name='cantidad',
        ),
    ]
